name: fifth workflow demo
on: workflow_dispatch

jobs:
  artifact-creation:
    runs-on: ubuntu-latest
    steps:
      - name: Create and edit file
        run: |
          touch "my_artifact_file"
          echo "some data in the file" > my_artifact_file
          cat my_artifact_file
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: uploaded_file_name
          path: /home/runner/work/githubactions_birminghamdemo/githubactions_birminghamdemo/my_artifact_file
