name: third workflow demo
on: [workflow_dispatch, push]
jobs:
  code-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Download code
        uses: actions/checkout@v4
  nginx-deploy-test:
    runs-on: ubuntu-latest
    steps:
      - name: Download container for testing
        run: |
          docker image pull nginx
          docker image ls
          docker container run -d -p 8080:80 nginx
      - name: Test web deployment with Python
        run: |
          python3 -c "import requests; r=requests.get('http://localhost:8080'); print(r.status_code)"
          curl -s localhost:8080
